import "./globals.css"
import { Inter } from "next/font/google"
import { Analytics } from "@/components/analytics"
import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
    title: "HAPI CSU",
    description: "Generated by create next app",
}

interface RootLayoutProps {
    children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
    return (
        <html lang="en">
            <body
                className={`antialiased min-h-screen bg-[#ffffff] dark:bg-slate-950 text-slate-900 dark:text-slate-50 ${inter.className}`}
            >
                <div>
                    <Navbar />
                    <main>{children}</main>
                    <Footer />
                </div>
                <Analytics />
            </body>
        </html>
    )
}
