import "./globals.css"
import { Inter } from "next/font/google"
import { ThemeProvider } from "@/components/theme-provider"
import { Analytics } from "@/components/analytics"
import Navbar from "@/components/Navbar"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
    title: "HAPI CSU",
    description: "Generated by create next app",
}

interface RootLayoutProps {
    children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
    return (
        <html lang="en">
            <body
                className={`antialiased min-h-screen bg-[#ffffff] dark:bg-slate-950 text-slate-900 dark:text-slate-50 ${inter.className}`}
            >
                <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
                    <div>
                        <Navbar />
                        <main>{children}</main>
                    </div>
                    <Analytics />
                </ThemeProvider>
            </body>
        </html>
    )
}
